spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: "forward:/fallback"

        - id: reservation-service
          uri: lb://RESERVATION-SERVICE
          predicates:
            - Path=/api/v1/reservations/**
          filters:
            - name: CircuitBreaker
              args:
                name: reservationServiceCircuitBreaker
                fallbackUri: "forward:/fallback"

        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/api/v1/libraries/**
          filters:
            - name: CircuitBreaker
              args:
                name: libraryServiceCircuitBreaker
                fallbackUri: "forward:/fallback"

        - id: rating-service
          uri: lb://RATING-SERVICE
          predicates:
            - Path=/api/v1/rating/**
          filters:
            - name: CircuitBreaker
              args:
                name: ratingServiceCircuitBreaker
                fallbackUri: "forward:/fallback"

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /manage
  endpoint:
    health:
      show-details: always
